(deftheme office
  "Created 2023-08-14.")

(custom-theme-set-faces
 'office
 '(cursor ((t (:background "#1874cd"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "steelblue1"))))
 '(highlight ((t (:weight bold :underline t))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "darkorange2"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#8b8970"))))
 '(font-lock-constant-face ((t (:foreground "#5d478b"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#00688b" :slant italic))))
 '(font-lock-keyword-face ((t (:foreground "#8b0a50"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#548b54"))))
 '(font-lock-type-face ((t (:foreground "#009acd"))))
 '(font-lock-variable-name-face ((t (:foreground "blue4"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit link))))
 '(link ((t (:underline t :foreground "darksalmon"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(header-line ((t (:inherit mode-line :background "#1d0526"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "#1874cd" :foreground "#fff8dc"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:inherit highlight :foreground "#ffe1ff"))))
 '(mode-line-inactive ((t (:weight light :foreground "#cdba96" :background "#8b7355" :inherit mode-line))))
 '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(custom-variable-tag ((t (:inherit font-lock-function-name-face))))
 '(show-paren-match ((t (:background "#b4eeb4"))))
 '(diff-refine-added ((t (:background "#336633" :inherit diff-refine-changed))))
 '(diff-refine-removed ((t (:background "#663333" :inherit diff-refine-changed))))
 '(diff-header ((t (:extend t :background "gray55"))))
 '(flycheck-warning ((t (:inherit warning :inverse-video t :underline t))))
 '(flycheck-error ((t (:inherit error))))
 '(flycheck-info ((t (:underline t :inverse-video t))))
 '(line-number ((t (:inherit (shadow default) :background "#c0d060" :foreground "wheat4"))))
 '(line-number-major-tick ((t (:inherit line-number-minor-tick :weight bold))))
 '(line-number-minor-tick ((t (:weight normal :inherit line-number :background "#b0c055"))))
 '(smerge-upper ((t (:inherit diff-removed :extend t))))
 '(smerge-lower ((t (:inherit diff-added :extend t))))
 '(sml/projectile ((t (:slant italic :inherit sml/git))))
 '(sml/modified ((t (:inherit sml/not-modified :foreground "indianred"))))
 '(sml/git ((t (:inherit sml/prefix))))
 '(sml/col-number ((t (:foreground "snow4"))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "dodgerblue" :weight bold))))
 '(undo-tree-visualizer-unmodified-face ((((class color)) (:foreground "cyan"))))
 '(hl-line ((t (:weight bold :background nil :foreground nil :underline t :overline t))))
 '(error ((t (:foreground "Red1" :inverse-video t :underline t :weight bold))))
 '(tree-sitter-hl-face:operator ((t (:inherit default))))
 '(web-mode-html-tag-bracket-face ((t (:foreground "#3a4b20"))))
 '(magit-section-highlight ((t (:inherit highlight))))
 '(tree-sitter-hl-face:function\.call ((t (:inherit (link font-lock-function-name-face) :foreground "#8a2be2" :underline nil))))
 '(smerge-refined-added ((t (:inherit smerge-refined-change :weight ultra-bold))))
 '(smerge-refined-removed ((t (:inherit smerge-refined-change :weight ultra-bold))))
 '(terraform--resource-name-face ((t (:inherit font-lock-function-name-face))))
 '(web-mode-html-attr-name-face ((t (:inherit font-lock-constant-face))))
 '(web-mode-html-tag-face ((t (:inherit font-lock-type-face))))
 '(default ((t (:foreground "black")))))

(provide-theme 'office)
